apps/store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    path('', ProductList.as_view(), name='store'),
    path('<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('categories/', CategoryList.as_view(), name='category-list'),
    path('categories/<slug:category_slug>/', ProductByCategoryList.as_view(), name='product-by-category'),
    path('checkout/<int:pk>/', Checkout.as_view(), name='checkout'),
]

apps/website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    #path('cookies-policy/', CookiesView.as_view(), name='cookies_policy'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.website.urls')),
    path('store/', include('apps.store.urls')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = "Liberté site admin (DEV)"
admin.site.site_header = "Mendri administration"
admin.site.index_title = "Ecommerce administration"

templates/partials/banner.html
{% load static %}

<div
  id="banner-carousel"
  data-interval="3000"
  class="w-full h-full flex relative overflow-hidden"
>

    <!-- {% for image in banner.get_images %} -->
        <div
          class="banner-image w-full h-full bg-cover bg-top absolute top-0 left-0 transform transition-transform {% if forloop.first %}translate-x-0{% else %}-translate-x-full{% endif %}"
          style="background-image: url(''); background-attachment: fixed;"
          >
        </div>
        <div
          class="banner-image w-full h-full bg-cover bg-top absolute top-0 left-0 transform transition-transform {% if forloop.first %}translate-x-0{% else %}-translate-x-full{% endif %}"
          style="background-image: url(''); background-attachment: fixed;"
          >
        </div>
        <div
          class="banner-image w-full h-full bg-cover bg-top absolute top-0 left-0 transform transition-transform {% if forloop.first %}translate-x-0{% else %}-translate-x-full{% endif %}"
          style="background-image: url(''); background-attachment: fixed;"
          >
        </div>
    <!-- {% endfor %} -->

  <div
    class="absolute inset-0 px-2 text-center flex flex-col justify-center items-center text-white gap-y-2"
  >
    {% if top_subtitle %}
        <h2 class="text-xl">Subtitulo</h2>
    {% endif %} 
    {% if title %}
        <h1 class="text-5xl md:text-6xl font-bold font-[monserrat]">Title</h1>
    {% endif %} 
    {% if not is_a_service and subtitle %}
        <h2 class="text-lg lg:text-xl font-normal">
            {{ subtitle }}{% if reading_time %} | {{ reading_time }} min{% endif %}
        </h2>
    {% endif %}
  </div>
</div>

templates/partials/button.html
<a
  class="text-{{ color }} hover:bg-gray-300 font-medium px-4 py-2 border border-{{ color }} mx-auto"
  href="{{ url }}"
>
  {{ text }} 
  {% if icon %} 
    {% include 'svg/icons/'|add:icon|add:'_icon.svg' with color=color size=icon_size %} 
  {% endif %}
</a>

templates/partials/checkout_modal.html
{% load humanize %}

<div class="fixed z-10 inset-0 overflow-y-auto hidden" id="modal">
  <div
    class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0"
  >
    <div class="fixed inset-0 transition-opacity" aria-hidden="true">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>

    <span
      class="hidden sm:inline-block sm:align-middle sm:h-screen"
      aria-hidden="true"
      >&#8203;</span
    >

    <div
      class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-title"
      aria-describedby="modal-description"
    >
      <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
        <div class="w-full flex items-center justify-end">
            <button
            onclick="closeModal()"
            class="hover:opacity-80"
          >
            {% include 'svg/icons/close_button.svg' with size=4 %}
          </button>
        </div>
        <!-- Contenido del modal -->
        <div class="pt-6 pb-12">
          <p>
            <strong class="font-medium">Gracias por confiar en nosotros</strong>, queremos comentarte que 
            finalizamos nuestras compras por <strong class="font-medium">WhatsApp</strong>. <br> 
            Nos gusta tener un <strong class="font-medium">trato personalizado</strong> con nuestros clientes. 
            Ahí coordinaremos la entrega del producto y el medio de pago. 
            <strong class="font-medium">¡Continuemos!</strong>
          </p>
        </div>

        <div class="w-full text-center pb-4">
          <a href="https://api.whatsapp.com/send?phone=+5491151016990&text=Hola, me gustaría finalizar la compra de '{{ product.name }}' con un valor total de ${{ product.price|intcomma }}. ¡Muchas gracias!" target="_blank" class="text-center text-white font-medium py-2 px-4 rounded-lg bg-[#ab8254] hover:bg-[#8f6c45]"
            >Continuar</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

templates/partials/cookies.html
<div
  class="cookie-notice hidden bg-gray-200 p-3 mx-auto w-screen md:w-fit leading-6 rounded fixed bottom-1 lg:bottom-0 left-0 right-0 md:left-10 md:right-10 z-[100] shadow-xl text-center"
  id="cookie-notice"
>
  <div class="flex items-center gap-x-4">
    <div>
      <h3 class="text-[#f4668c] font-semibold">Cookies</h3>
      <p class="text-sm">
        Utilizamos cookies propias y de terceros para mejorar nuestros
        servicios.
      </p>
      <a
        class="text-blue-500 hover:underline text-xs"
        href="{% url 'website:cookies_policy' %}"
        >Aviso de Cookies</a
      >
    </div>

    <button
      class="mx-auto bg-[#f4668c] hover:bg-[#dd5d7f] text-white text-sm font-semibold py-3 px-4 rounded-xl transition duration-300"
      id="btn-accept-cookies"
    >
      De acuerdo
    </button>
  </div>
</div>

<div
  class="cookie-notice-bg hidden bg-black bg-opacity-20 fixed z-[99] w-full h-full top-0 left-0"
  id="cookie-notice-bg"
></div>

<style>
  .cookie-notice {
    z-index: 10000000000 !important;
  }
</style>

templates/partials/footer.html
<footer
  class="w-full bg-[#140f0e] text-white pt-10 pb-4 px-4 sm:px-6 md:px-20 lg:px-36"
>
  <div
    class="w-full max-w-screen-lg md:h-full mx-auto flex flex-col items-center md:flex-row md:items-stretch gap-y-10 md:gap-x-10"
  >

      <ul
          class="text-lg w-full flex flex-col lg:flex-row mx-auto items-center justify-center gap-y-4 md:gap-y-8 md:py-4 sm:gap-x-6"
        >
          <li class="font2 text-xl text-center md:text-2xl lg:text-base hover:opacity-80">
            <a href="{% url 'store:store' %}">Tienda</a>
          </li>
          <li class="text-xl text-center md:text-2xl lg:text-base hover:opacity-80">
            <a href="{% url 'website:about' %}">Sobre nosotros</a>
          </li>
          <li class="text-xl text-center md:text-2xl lg:text-base hover:opacity-80">
            <a href="{% url 'website:contact' %}">Contacto</a>
          </li>
      </ul>
 
  </div>

  <div class="w-full pt-8 pb-4">
    <p class="text-sm text-center">
      &copy; 2023 - Todos los derechos reservados.
    </p>
  </div>
</footer>

templates/partials/header.html
<header
  class="relative w-full h-[50vh] lg:h-[70vh] bg-[#140f0e] pt-20 flex flex-col justify-center items-center md:items-start"
>
  {% if banner %}
      <!-- <div class="w-full h-full bg-black bg-opacity-10 absolute inset-0 z-10"></div> -->
      <div class="w-full h-full absolute inset-0 ">
        <img src="{{ banner.image_1.url }}" alt="" class="w-full h-full object-cover object-center">
      </div>
  {% endif %}

  <div class="max-w-screen-2xl text-[#FFDFBA] bg-black bg-opacity-40 z-20 w-full mx-auto px-4 sm:px-8 md:px-16 py-10 text-{{ align }}">
      
    <h2 class="text-xl"></h2>

      <h1 class="font2 text-5xl lg:text-7xl font-semibold py-2">{{ title }}</h1>

      {% if subtitle %}
        <h2 class="text-xl lg:text-2xl font-normal py-2">{{ subtitle }}</h2>
      {% endif %}
  </div>

</header>

templates/partials/navbar.html
{% load static %}

<nav
  id="navbar"
  class="bg-[#140f0e] bg-opacity-0 text-black h-20 top-0 w-full mx-auto overflow-hidden p-4 md:px-8 lg:px-10 2xl:px-20 fixed flex items-center justify-between z-50 transition transition-opacity duration-500 ease-in-out"
>
  

  <!-- Mobile buttons -->
  <input type="checkbox" id="menu" class="peer hidden" />

  <!-- Brand -->
  <a href="{% url 'website:home' %}" class="font2 text-white text-lg border-b z-50 peer-checked:opacity-0">
    <!-- <img src="" alt="Logo de " height="30" /> -->
    Liberté
  </a>
  
    <label
      id="openMenuButton"
      for="menu"
      class="peer-checked:hidden lg:hidden h-30 w-30 cursor-pointer transition-all z-50"
      >
      {% include 'svg/icons/mobile_menu_button.svg' %}
    </label>

    <label
      id="closeMenuButton"
      for="menu"
      class="hidden peer-checked:block lg:hidden h-30 w-30 cursor-pointer transition-all z-50"
      >
      {% include 'svg/icons/close_button.svg' with size=7 %}
    </label>

  <div
    id="navbarLinksContainer"
    class="w-screen lg:w-auto h-screen bg-gray-200 lg:bg-transparent lg:h-full overflow-hidden fixed lg:static left-0 top-0 py-8 lg:py-0 translate-x-full lg:translate-x-0 peer-checked:translate-x-0 transition-all ease-in-out z-40"
  >
  
    <ul class="w-full h-full pt-16 lg:bg-transparent lg:text-gray-100 flex flex-col lg:flex-row items-center lg:items-center justify-start pt-16 lg:pt-0 gap-16 lg:gap-x-10">

      <li class="font2 text-xl md:text-2xl lg:text-base hover:opacity-80">
        <a href="{% url 'store:store' %}" class="lg:text-gray-100 font-medium">
          Tienda
        </a>
      </li>
      <li class="text-xl md:text-2xl lg:text-base hover:opacity-80">
        <a href="{% url 'website:about' %}">Sobre nosotros</a>
      </li>
      <li
        class="text-xl md:text-2xl lg:text-base hover:opacity-80"
      >
        <a href="{% url 'website:contact' %}">Contacto</a>
      </li>
      
    </ul>
  </div>
</nav>

<script>
    const navbar = document.getElementById('navbar');
    const menuCheckBox = document.getElementById('menu');
    const openMenuButton = document.getElementById('openMenuButton');
    const closeMenuButton = document.getElementById('closeMenuButton');
    const navbarLinksContainer = document.getElementById('navbarLinksContainer');

    window.addEventListener('scroll', () => {
      let scroll = window.scrollY;
    
      if (scroll > 50) {
        navbar.classList.add('bg-opacity-50');
      } else {
        navbar.classList.remove('bg-opacity-50');
      }
    });
</script>

templates/partials/product_card.html
<a href="{% url 'store:product-detail' product.pk %}" class="group relative">
  <div class="aspect-[2/3] w-full overflow-hidden">
    <img src="{{ product.thumbnail_image.url }}" alt="Imagen de {{ product.name }}." class="h-full w-full object-cover object-center group-hover:opacity-75">
  </div>
  <div class="absolute left-0 bottom-0 w-full h-[30%] bg-black bg-opacity-50 text-white flex flex-col items-center justify-between gap-y-2 px-3 pt-2 pb-6 h-28 z-10">
    
    <h3 class="w-full text-sm">
      {{ product.name }}
    </h3>

    <div class="w-full flex items-center justify-between h-[20%]">
      <div class="">
        {% if product.is_unique %}
        <p class="mt-1 text-xs text-[#FFDFBA]">Producto único</p>
        {% else %}
        <p class="mt-1 text-xs text-gray-200">Stock: {{ product.stock }}</p>
        {% endif %}
      </div>
  
      <p class="text-lg font-medium">${{ product.price }}</p>
    </div>
  </div>
</a>

templates/partials/products_list.html
{% load static %}

<div class="bg-gray-100">
  <div class="mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
    <h2 class="sr-only">Products</h2>

    <div class="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">

      {% for product in products %} 
        {% include 'partials/product_card.html' with product=product %}
      {% endfor %}

    </div>
  </div>
</div>

templates/partials/selected_products.html
<section class=" w-full flex flex-col flex-wrap">

    {% if title %}
        <a
            href="{% url 'store:store' %}"
            class="w-full pt-10"
        >
            <h2 class="inline font-medium text-2xl lg:text-3xl lg:font-normal border-1 hover:border-b border-zinc-800">
                {{ title }}
            </h2>
        </a>
    {% endif %}
    <div class="w-full overflow-y-auto gap-6 flex flex-col flex-wrap">   
        <div class="py-6 gap-6 flex lg:grid lg:grid-cols-4">
            {% for product in products %}
                <div class="w-[60vw] md:w-[30vw] lg:w-[20vw] h-full">
                    {% include 'partials/product_card.html' with product=product %}
                </div>
            {% endfor %}
        </div>
    </div>
    
  </section>

templates/partials/share_buttons.html
<ul id="share-buttons-container" data-url="{{ url }}" class="flex items-center justify-center gap-x-4">
    <li>
        <button id="shareFacebook">
            {% include 'svg/icons/facebook_icon.svg' with color='[#f4668c]' size=6 %}
        </button>
    </li>
    <li>
        <button id="shareTwitter">
            {% include 'svg/icons/twitter_icon.svg' with color='[#f4668c]' size=6 %}
        </button>
    </li>
    <li>
        <a href="mailto:?body={{ url }}">
            {% include 'svg/icons/email_icon.svg' with color='[#f4668c]' size=5 %}
        </a>
    </li>
    <li>
        <button id="shareWhatsApp">
            {% include 'svg/icons/whatsapp_icon.svg' with color='[#f4668c]' size=6 %}
        </button>
    </li>
</ul>
  

templates/partials/social_links.html
{% load static %}

<ul class="w-full flex flex-{{ direction }} justify-{{ spacign }} items-center gap-8">

  <li>
    <a href="{{ social_links.instagram }}" target="_blank">
      {% include 'svg/icons/instagram_icon.svg' with color=icon_color size=icon_size %}
    </a>
  </li>

  <li>
    <a href="{{ social_links.tiktok }}" target="_blank">
      {% include 'svg/icons/facebook_icon.svg' with color=icon_color size=icon_size %}
    </a>
  </li>

  <li>
    <a href="mailto:{{ social_links.email }}" target="_blank">
      {% include 'svg/icons/email_icon.svg' with color=icon_color size=icon_size %}
    </a>
  </li>
  
</ul>

templates/partials/wsp_button.html
{% load static %}

<a href="https://api.whatsapp.com/send?phone=+5491151016990&text=Hola, me gustaría realizar una consulta. ¡Muchas gracias!" target="_blank" class="fixed w-14 aspect-square z-50 bottom-6 right-6 p-1 bg-[#28e763] rounded-full">
    {% include 'svg/icons/whatsapp_icon.svg' with color='white' size=12 %}
</a>