apps/store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    path('', ProductList.as_view(), name='store'),
    path('<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('categories/', CategoryList.as_view(), name='category-list'),
    path('categories/<slug:category_slug>/', ProductByCategoryList.as_view(), name='product-by-category'),
    path('checkout/<int:pk>/', Checkout.as_view(), name='checkout'),
]

apps/website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    #path('cookies-policy/', CookiesView.as_view(), name='cookies_policy'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.website.urls')),
    path('store/', include('apps.store.urls')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = "Liberté site admin (DEV)"
admin.site.site_header = "Mendri administration"
admin.site.index_title = "Ecommerce administration"

apps/store/models/Category.py
from django.db.models import Model, CharField, SlugField, IntegerField, ImageField


class Category(Model):
    name = CharField(max_length=100, verbose_name='Nombre')
    slug = SlugField(max_length=100, unique=True, verbose_name='Slug')
    position = IntegerField(verbose_name='Posición')
    thumbnail_image = ImageField(upload_to='categories/thumbnails/', verbose_name='Imagen en miniatura')

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        ordering = ('position',)

    def __str__(self):
        return self.name

apps/store/models/Product.py
from django.db.models import Model, CharField, TextField, IntegerField, DecimalField, BooleanField, ImageField, ForeignKey, CASCADE

from .Category import Category


class Product(Model):
    name = CharField(max_length=100, verbose_name='Nombre')
    category = ForeignKey(Category, on_delete=CASCADE, related_name='product', verbose_name='Categoría')
    description = TextField(verbose_name='Descripción')
    highlight_1 = CharField(blank=True, null=True, max_length=100, verbose_name='Item destacado 1')
    highlight_2 = CharField(blank=True, null=True, max_length=100, verbose_name='Item destacado 2')
    highlight_3 = CharField(blank=True, null=True, max_length=100, verbose_name='Item destacado 3')
    highlight_4 = CharField(blank=True, null=True, max_length=100, verbose_name='Item destacado 4')
    details = TextField(blank=True, null=True, verbose_name='Detalles')
    price = DecimalField(max_digits=10, decimal_places=0, verbose_name='Precio')
    stock = IntegerField(default=1, verbose_name='Stock')
    is_unique = BooleanField(default=True, verbose_name='¿Es un producto único?')
    is_selected = BooleanField(default=False, verbose_name='¿Mostrar en productos seleccionados?')
    thumbnail_image = ImageField(upload_to='store/thumbnails/', verbose_name='Imagen en miniatura')

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.name

apps/store/models/ProductImage.py
from django.db.models import Model, IntegerField, ImageField, ForeignKey, CASCADE

from .Product import Product


class ProductImage(Model):
    product = ForeignKey(Product, related_name='images', on_delete=CASCADE, verbose_name='Producto')
    position = IntegerField(verbose_name='Posición')
    image = ImageField(upload_to='store/images/', verbose_name='Imagen')

    class Meta:
        verbose_name = 'Imagen de Producto'
        verbose_name_plural = 'Imágenes de Productos'

    def __str__(self):
        return f"Imagen de {self.product.name}"

apps/store/models/StorePage.py
from django.db.models import Model, CharField, ForeignKey, PROTECT

from apps.website.models import Banner


class StorePage(Model):
    class Meta:
        verbose_name = 'Página de la Tienda'
        verbose_name_plural = 'Página de la Tienda'

    top_subtitle = CharField(max_length=255, blank=True, null=True, verbose_name='Subtítulo superior')
    title = CharField(max_length=255, blank=True, null=True, verbose_name='Título')
    subtitle = CharField(max_length=255, blank=True, null=True, verbose_name='Subtítulo inferior')
    banner = ForeignKey(Banner, on_delete=PROTECT, blank=True, null=True)

    def __str__(self) -> str:
        return 'Tienda'

apps/store/views.py
from django.views.generic import TemplateView, ListView, DetailView

from .models import Product, Category, ProductImage, StorePage


class ProductList(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'pages/store.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['page'] = StorePage.objects.first()
        context['categories'] = Category.objects.all()

        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'pages/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        product = self.get_object()

        context['product'] = product
        highlights = [
            product.highlight_1,
            product.highlight_2,
            product.highlight_3,
            product.highlight_4
        ]
        # Filtrar los campos que no estén vacíos (no sean None o cadenas vacías)
        filtered_highlights = [highlight for highlight in highlights if highlight]

        # Agregar al contexto solo si hay algún contenido
        if filtered_highlights:
            context['highlights'] = filtered_highlights

        context['images'] = ProductImage.objects.filter(product=product.id)

        return context


class CategoryList(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'pages/categories.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['page'] = StorePage.objects.first()

        return context


class ProductByCategoryList(TemplateView):
    template_name = 'pages/store.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        category_slug = self.kwargs.get('category_slug')
        context['products'] = Product.objects.filter(category__slug=category_slug).select_related('category')
        context['categories'] = Category.objects.all()
        context['page'] = StorePage.objects.first()

        return context


class Checkout(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'pages/checkout.html'




'''class ProductDetail(RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductByCategoryList(ListAPIView):
    serializer_class = ProductSerializer

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        category = get_object_or_404(Category, slug=category_slug)
        return Product.objects.filter(category=category)


class CategoryList(ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer'''

templates/pages/about.html
{% extends 'base.html' %} 
{% load static %} 

{% block description %}
<meta name="description" content="Blog de viajes: Descubre artículos, consejos de viaje y aventuras alrededor del mundo. ¡Inspírate para tu próximo destino!">
{% endblock description %}

{% block title %}Sobre nosotros{% endblock title %} 

{% block header %}
    {% include 'partials/header.html' with align='center' title=page.title subtitle=page.subtitle banner=page.banner %}
{% endblock header %}

{% block main %}
<main class=" max-w-screen-2xl w-full mx-auto px-8 sm:px-16 md:px-32 pb-20 md:pt-20">
    <section class="w-full mx-auto">
        <article class="content-container w-full mx-auto py-12">
            <p class="text-lg">
                {{ page.content | safe }}
            </p>
        </article>
    </section>
</main>
{% endblock main %} 

{% block scripts %}{% endblock scripts %}

templates/pages/categories.html
{% extends 'base.html' %} 
{% load static %} 

{% block description %}
<meta name="description" content="">
{% endblock description %}

{% block head %}{% endblock head %}

{% block title %}Categorías{% endblock %}

{% block main %}
<main class="mx-auto py-20">

  {% if categories %}

        <section class="bg-gray-100">
            <div class="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10">
              <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
                <h2 class="text-2xl font-bold text-gray-900">Colecciones</h2>
          
                
                <div class="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
        
                    {% for category in categories %}
                    <article class="group relative">
                        <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
                        <img src="{{ category.thumbnail_image.url }}" alt="Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug." class="h-full w-full object-cover object-center">
                        </div>
                        <h3 class="mt-6 text-base font-semibold text-gray-900">
                        <a href="{% url 'store:product-by-category' category.slug %}">
                            <span class="absolute inset-0"></span>
                            {{ category.name }}
                        </a>
                        </h3>
                    </article>
                    {% endfor %}
        
                </div>
              </div>
            </div>
          </section> 

  {% endif %}

</main>
{% endblock main %} 

templates/pages/contact.html
{% extends 'base.html' %}
{% load static %} 

{% block description %}
<meta name="description" content="¡Contáctanos! Estamos encantados de escuchar tus preguntas, comentarios o sugerencias. Completa el formulario de contacto y únete a nuestra comunidad de viajeros.">
{% endblock description %}

{% block head %}
{{ block.super }}
<!-- Start International Telephone Input -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/css/intlTelInput.css">
<!-- End International Telephone Input -->
<!-- Start Google reCAPTCHA -->
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<!-- End Google reCAPTCHA -->
{% endblock head %}

{% block title %}Contacto{% endblock %}

{% block header %}
    {% include 'partials/header.html' with align='center' title='Contacto' %}
{% endblock header %}

{% block main %}
<main class="max-w-7xl mx-auto py-20 lg:pt-0 lg:grid lg:grid-cols-1">
    <section class="max-w-screen-2xl bg-[#140f0e] w-full lg:w-fit mx-auto px-8 sm:px-16 lg:px-40 py-16  lg:mt-20 2xl:mt-0 lg:py-28 lg:flex flex-col justify-start 2xl:justify-center items-center">
        {% include 'partials/social_links.html' with icon_color='white' social_links=generals.social_links icon_size=10 direction='row' spacign='center' %}
    </section>
</main>
{% endblock main %}

{% block scripts %}{% endblock scripts %}

templates/pages/cookies_policy.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Aviso de Privacidad</title>
  </head>
  <body>
    <main>
      <a href="{% url 'website:home' %}"> Regresar </a>
      <h1>Aviso de Cookies</h1>
      <h3>¿Qué son las cookies?</h3>
      <p>
        Una cookie es un fichero que se descarga en su ordenador al acceder a
        determinadas páginas web. Las cookies permiten a una página web, entre
        otras cosas, almacenar y recuperar información sobre los hábitos de
        navegación de un usuario o de su equipo y, dependiendo de la información
        que contengan y de la forma en que utilice su equipo, pueden utilizarse
        para reconocer al usuario.
      </p>

      <h3>¿Qué tipos de cookies utiliza esta página web?</h3>
      <p>Esta página web utiliza los siguientes tipos de cookies:</p>

      <p>
        <b>Cookies de análisis:</b> Son aquéllas que bien tratadas por nosotros
        o por terceros, nos permiten cuantificar el número de usuarios y así
        realizar la medición y análisis estadístico de la utilización que hacen
        los usuarios del servicio ofertado. Para ello se analiza su navegación
        en nuestra página web con el fin de mejorar la oferta de productos o
        servicios que le ofrecemos.
      </p>

      <p>
        <b>Cookies técnicas:</b> Son aquellas que permiten al usuario la
        navegación a través del área restringida y la utilización de sus
        diferentes funciones, como por ejemplo, llevar a cambio el proceso de
        compra de un artículo.
      </p>

      <p>
        <b>Cookies de personalización:</b> Son aquellas que permiten al usuario
        acceder al servicio con algunas características de carácter general
        predefinidas en función de una serie de criterios en el terminal del
        usuario como por ejemplo serian el idioma o el tipo de navegador a
        través del cual se conecta al servicio.
      </p>

      <p>
        <b>Cookies publicitarias:</b> Son aquéllas que, bien tratadas por esta
        web o por terceros, permiten gestionar de la forma más eficaz posible la
        oferta de los espacios publicitarios que hay en la página web, adecuando
        el contenido del anuncio al contenido del servicio solicitado o al uso
        que realice de nuestra página web. Para ello podemos analizar sus
        hábitos de navegación en Internet y podemos mostrarle publicidad
        relacionada con su perfil de navegación.
      </p>

      <p>
        <b>Cookies de publicidad comportamental:</b> Son aquellas que permiten
        la gestión, de la forma más eficaz posible, de los espacios
        publicitarios que, en su caso, el editor haya incluido en una página
        web, aplicación o plataforma desde la que presta el servicio solicitado.
        Este tipo de cookies almacenan información del comportamiento de los
        visitantes obtenida a través de la observación continuada de sus hábitos
        de navegación, lo que permite desarrollar un perfil específico para
        mostrar avisos publicitarios en función del mismo.
      </p>

      <h3>Desactivar las cookies.</h3>
      <p>
        Puede usted permitir, bloquear o eliminar las cookies instaladas en su
        equipo mediante la configuración de las opciones del navegador instalado
        en su ordenador.
      </p>

      <p>
        En la mayoría de los navegadores web se ofrece la posibilidad de
        permitir, bloquear o eliminar las cookies instaladas en su equipo.
      </p>

      <p>
        A continuación puede acceder a la configuración de los navegadores webs
        más frecuentes para aceptar, instalar o desactivar las cookies:
      </p>

      <p>
        <a
          href="https://support.google.com/chrome/answer/95647?hl=es"
          target="_blank"
          rel="noopener"
          >Configurar cookies en Google Chrome</a
        >
      </p>

      <p>
        <a
          href="http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9"
          target="_blank"
          rel="noopener"
          >Configurar cookies en Microsoft Internet Explorer</a
        >
      </p>

      <p>
        <a
          href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectlocale=es&amp;redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we"
          target="_blank"
          rel="noopener"
          >Configurar cookies en Mozilla Firefox</a
        >
      </p>

      <p>
        <a
          href="https://support.apple.com/es-es/HT201265"
          target="_blank"
          rel="noopener"
          >Configurar cookies en Safari (Apple)</a
        >
      </p>

      <h3>Cookies de terceros.</h3>

      <p>
        Esta página web utiliza servicios de terceros para recopilar información
        con fines estadísticos y de uso de la web. Se usan cookies de
        DoubleClick para mejorar la publicidad que se incluye en el sitio web.
        Son utilizadas para orientar la publicidad según el contenido que es
        relevante para un usuario, mejorando así la calidad de experiencia en el
        uso del mismo.
      </p>

      <p>
        En concreto, usamos los servicios de Google Adsense y de Google
        Analytics para nuestras estadísticas y publicidad. Algunas cookies son
        esenciales para el funcionamiento del sitio, por ejemplo el buscador
        incorporado.
      </p>

      <p>
        Nuestro sitio incluye otras funcionalidades proporcionadas por terceros.
        Usted puede fácilmente compartir el contenido en redes sociales como
        Facebook, Twitter o Google +, con los botones que hemos incluido a tal
        efecto.
      </p>

      <h3>Advertencia sobre eliminar cookies.</h3>

      <p>
        Usted puede eliminar y bloquear todas las cookies de este sitio, pero
        parte del sitio no funcionará o la calidad de la página web puede verse
        afectada.
      </p>

      <p>
        Si tiene cualquier duda acerca de nuestra política de cookies, puede
        contactar con esta página web a través de nuestros canales de Contacto.
      </p>
    </main>
  </body>
</html>

templates/pages/home.html
{% extends 'base.html' %} 
{% load static %} 

{% block description %}
<meta name="description" content="">
{% endblock description %}

{% block head %}{% endblock head %}

{% block title %}Buenos Aires{% endblock %}

{% block header %}
    {% include 'partials/header.html' with align='center' title=page.title subtitle=page.subtitle banner=page.banner %}
{% endblock header %}

{% block main %}
<main class="bg-gray-200 mx-auto">

  {% if selected_products %}
      <section class="max-w-screen-2xl w-full mx-auto space-y-8 py-10 px-4 sm:px-8 md:px-16">
          {% include 'partials/selected_products.html' with products=selected_products %}
          <div class="w-full mx-auto text-center sm:px-16 md:px-32">
              {% include 'partials/button.html' with url='/store' text='Ver más' align='center' color='[#140f0e]' icon_size=4 %}
          </div>
      </section>
  {% endif %}

  <section class="max-w-screen-2xl pt-10 pb-20  w-full mx-auto lg:grid grid-cols-2 lg:px-16">
    
    <article class="group relative max-h-90 h-90 lg:h-[80vh]">

      <div
        class="w-full h-full overflow-hidden lg:aspect-none group-hover:opacity-80"
      >
        <img
          src="{% static 'img/productos-unicos2.jpg' %}"
          alt="Imagen de ."
          class="h-full w-full object-cover object-center"
        />
      </div>

      
      <h3 class="absolute inset-0 h-full w-full px-3">
        <a href="{% url 'store:store' %}" class="flex flex-col items-center justify-center h-full w-full">
            <span aria-hidden="true" class="text-white text-2xl md:text-5xl lg:text-2xl uppercase">Productos únicos</span>
        </a>
      </h3>
      
    </article>

    <article class="group relative h-90 lg:h-[80vh]">

      <div
        class="w-full h-full overflow-hidden lg:aspect-none group-hover:opacity-80 lg:aspect-w-1 "
      >
        <img
          src="{% static 'img/productos-en-stock2.jpg' %}"
          alt="Imagen de ."
          class="h-full w-full object-cover object-center"
        />
      </div>

      <h3 class="absolute inset-0 h-full w-full px-3">
        <a href="{% url 'store:store' %}" class="flex flex-col items-center justify-center h-full w-full">
            <span aria-hidden="true" class="text-white text-2xl md:text-5xl lg:text-2xl uppercase">Productos en stock</span>
        </a>
      </h3>
      
    </article>

  </section>

  

</main>
{% endblock main %} 

{% block scripts %}{% endblock scripts %}

templates/pages/product_detail.html
{% extends 'base.html' %} 

{% load humanize %}
{% load static %} 

{% block description %}
<meta name="description" content="">
{% endblock description %}

{% block head %}
  {{ block.super }}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css" rel="stylesheet" />
{% endblock head %}

{% block title %}Tienda - {{ product.name }}{% endblock title %} 

{% block main %}
<main
  class="w-full pb-16"
>
<div class="bg-[#140f0e] w-full h-20"></div>
<div class="bg-white border-t mx-auto md:px-20 space-y-8">

    <div class="w-full lg:flex items-center">

      <div class="w-full h-max lg:w-[60%]">

      <!-- Breadcrumb -->
      <nav aria-label="Breadcrumb" class="h-full lg_w-full p-4 lg:py-8">
        <ol role="list" class="lg:w-full mx-auto flex max-w-2xl items-center lg:justify-start space-x-2 px-4 sm:px-6 lg:max-w-7xl lg:px-8">
          <li>
            <div class="flex items-center lg:justify-start ">
              <a href="{% url 'store:store' %}" class="mr-2 text-sm font-medium text-gray-900">Tienda</a>
              <svg width="16" height="20" viewBox="0 0 16 20" fill="currentColor" aria-hidden="true" class="h-5 w-4 text-gray-300">
                <path d="M5.697 4.34L8.98 16.532h1.327L7.025 4.341H5.697z" />
              </svg>
            </div>
          </li>
          <li>
            <div class="flex items-center">
              <a href="{% url 'store:product-by-category' product.category.slug %}" class="mr-2 text-sm font-medium text-gray-900">{{ product.category }}</a>
              <svg width="16" height="20" viewBox="0 0 16 20" fill="currentColor" aria-hidden="true" class="h-5 w-4 text-gray-300">
                <path d="M5.697 4.34L8.98 16.532h1.327L7.025 4.341H5.697z" />
              </svg>
            </div>
          </li>
  
          <li class="text-sm">
            <a href="#" aria-current="page" class="font-medium text-gray-500 hover:text-gray-600">{{ product.name }}</a>
          </li>
        </ol>
      </nav>
  
      <!-- Image gallery -->
      <section class="mx-auto max-w-2xl  lg:gap-x-6 lg:px-8">

        <div class="aspect-[1/1] overflow-hidden rounded-lg lg:block">
          <img src="{{ product.thumbnail_image.url }}" alt="1" class="h-full w-full object-cover object-center">
        </div>

        

        
  
      </section>
      </div>
  
      <!-- Product info -->
      <section class="w-full h-full lg:w-[40%] mx-auto max-w-2xl px-4 pb-16 pt-10 sm:px-6 lg:max-w-7xl lg:gap-x-8 lg:px-8 lg:pb-24 lg:pt-16">

        <div class="lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
          <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">{{ product.name }}</h1>
        </div>
  
        <!-- Price -->
        <div class="mt-4 lg:row-span-3 lg:mt-0">
          <h2 class="sr-only">Información del producto</h2>
          <p class="text-3xl tracking-tight text-gray-900">${{ product.price|intcomma }}</p>
  
          <!-- Stock -->
          <div class="mt-6">
            <div class="flex items-center">
              {% if product.is_unique %}
              <h3 class="p-2 font-medium text-[#ab8254]">Producto único</h3>
              {% else %}
              <h3 class="ml-3 text-sm font-medium text-gray-600">Stock: {{ product.stock }}</h3>
              {% endif %}
            </div>
          </div>
          
          <!-- Buy button -->
          <a href="{% url 'store:checkout' product.pk %}" class="mt-10 flex w-full items-center justify-center rounded-md border border-transparent bg-[#ab8254] hover:bg-[#8f6c45] px-8 py-3 text-base font-medium text-white focus:outline-none focus:ring-none focus:ring-indigo-500 focus:ring-offset-2">
            {% include 'svg/icons/cart_icon.svg' with size=6 %}
            Comprar
          </a>
  
        </div>
        
      </section>

    </div>

    <div class="w-full flex flex-row items-center justify-between gap-x-8">

      <section class="w-full lg:w-1/2">
        {% if images %}
        <div class="hidden lg:grid lg:grid-cols-2 lg:gap-6">
          {% for item in images %}
          <div class="aspect-[1/1] overflow-hidden">
            <img src="{{ item.image.url }}" alt="2" class="h-full w-full object-cover object-center">
          </div>
          {% endfor %}
        </div>
      {% endif %}
      </section>

      <section class="w-full lg:w-1/2 py-10 lg:pt-24 px-6 lg:col-span-2 lg:col-start-1 lg:border-r lg:border-gray-200 lg:pb-16 lg:pr-8">
        <!-- Description and details -->
        <div>
          <h3 class="sr-only">Descripción</h3>
  
          <div class="space-y-6">
            <p class="text-lg text-gray-900">{{ product.description }}</p>
          </div>
        </div>
        {% if highlights %}
        <div class="mt-10">
          <h3 class="font-medium text-gray-900">Destacados</h3>
  
          <div class="mt-4">
            <ul role="list" class="list-disc space-y-2 pl-4">
              {% for highlight in highlights %}
  
              <li class="text-gray-400"><span class="text-gray-600">{{ highlight }}</span></li>
  
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}
        {% if product.details %}
        <div class="mt-10">
          <h2 class="text-sm font-medium text-gray-900">Detalles</h2>
  
          <div class="mt-4 space-y-6">
            <p class="text-sm text-gray-600">{{ product.details }}</p>
          </div>
        </div>
        {% endif %}
      </section>

    </div>

    
</div>

</main>
{% endblock main %}

{% block scripts %} 
{{ block.super }} 
<script src="{% static 'js/shareArticle.js' %}"></script>
{% endblock scripts %}

templates/pages/store.html
{% extends 'base.html' %} 

{% load static %} 

{% block description %}
<meta name="description" content="">
{% endblock description %}

{% block head %} {% endblock head %} 

{% block title %}Tienda{% endblock title %} 

{% block header %}
    {% include 'partials/header.html' with align='center' title=page.title subtitle=page.subtitle banner=page.banner %}
{% endblock header %}

{% block main %}
<main class="w-full bg-white mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pb-4">

        <section class="flex items-baseline justify-between border-b border-gray-200 pb-6 md:pt-10 md:px-10 lg:px-0">
          <h2 class="text-4xl hidden md:block tracking-tight">Productos</h2>
        </section>
  
        <section aria-labelledby="products-heading" class="pb-24 pt-6 px-6">
          <h2 id="products-heading" class="sr-only">Productos</h2>
  
          <div class="flex flex-col lg:flex-row lg:items-start items-center gap-x-8 gap-y-10 ">

            {% if categories %} 
            <!-- Filters -->
            <div class="w-fit md:w-fit lg:w-[10%] lg:mx-auto">

              <h3 class="sr-only">Categorías</h3>
              
              <ul role="list" class="flex lg:flex-col lg:justify-start justify-center items-center flex-wrap gap-4 border-b border-gray-200 pb-6  text-sm font-medium text-gray-900">
                <li class="lg:w-full">
                  <a href="{% url 'store:store' %}" class="{% if not category_slug %}font-semibold border-b border-[#140f0e]{% endif %}">Todos</a>
                </li>
                {% for category in categories %}
                <li class="lg:w-full">
                  <a href="{% url 'store:product-by-category' category.slug %}" class="{% if category_slug == category.slug %}font-semibold border-b border-[#140f0e]{% endif %}">{{ category.name }}</a>
                </li>
                {% endfor %}
              </ul>
              
            </div>
            {% endif %} 

            <!-- Product grid -->
            {% if products %} 
              <section class="w-full lg:w-[90%] bg-gray-100">
                {% include 'partials/products_list.html' with products=products %}
              </section>
            {% endif %} 

          </div>
        </section>
        
</main>
{% endblock main %} 

{% block scripts %}{% endblock scripts %}